const express = require('express') 
const { userDetailsController } = require('../controllers/userController.js')
const { auth } = require('../middlewares/auth.js')

const router = express.Router()

// router.put('/updateJoiningDetails', updateJoiningDetailsController)
// router.post('/getUserDetails', [auth], userDetailsController)
router.post('/getUserDetails', userDetailsController)
// router.get('/getUserNameByReferralId/:referralCode', userNameByReferralCodeController)
// router.get('/getRootCodeByReferralCode/:referralCode', rootReferralCodeByReferralCode)
// router.get('/getLevelWiseIncome/:level', [auth], levelWiseIncomeDetails)
// router.get('/getDirectIncome', [auth], directIncomeDetails)
// router.get('/getBusinessHistory', [auth], businessHistoryController)
// router.get('/getAllTeamMember', [auth], getAllTeamMember)
// router.get('/getDirectTeamMember', [auth], getDirectTeamMember)
// router.get('/getTransactionHistory', [auth], getTransactionHistory)
// router.post('/deposit', [auth], depositAmount)
// router.post('/withdraw', [auth], withdrawAmount)
// router.put('/updateAutoTop', [auth], updateAutoTopupEnabled)
// router.post('/generateOtpForWithdraw', [auth], generateOtpForWithdrawController)
// router.post('/manualTopup', [auth], manualTopup)
// router.post('/generateOtpForPasscodeReset', generateOtpForPasscodeResetController)
// router.put('/resetPasscode', resetPasscodeController)
// router.put('/updateProfileImage', [auth], updateUserProfileImage)
// router.put('/updateProfileDetails', [auth], updateUserProfileDetails)
// router.get('/getMemberTree', [auth], getMemberTree)

module.exports = router